version: 2

updates:
  - package-ecosystem: npm
    directory: /
    target-branch: development
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore(deps)
    groups:
      production:
        dependency-type: production
        update-types: [minor, patch]
      development:
        dependency-type: development
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    target-branch: development
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: ci(deps)
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /docker
    target-branch: development
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: build(deps)
